### ISSUE TITLE
Additional student question features

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2265]
### general

- [ ] direct navigation from submission to question dashboard
- [ ] direct navigation from submission linked to question to latest submission (after posing question, student may have newer submissions for the same exercise) or other submissions for the same exericise in general
- [ ] allow students to ask a question on an exercise, a series or a course (not a specific submission); would also allow to ask question on reading assignments (#2329)
- [ ] link question and answer in discussion thread; upon answering question, course admin is asked if state needs to be changed (start of answering > mark as in progress if no already the case; end of answering > mark as answered if not already the case)
- [ ] course admins should see the “ask a question” features on their own submissions, instead of the “code review” features (this way they can also demo the feature)
- [ ] if student asks multiple questions on the same submission, we still might have multiple course managers working on the same submission (student might e.g. ask a second question after course manager started answering the first question)
- [ ] students indicate that they have asked a question, but no answer has arrived yet; this is due to the fact that they have no clue where they are in the queue; some indication about "number of questions waiting in front of your" or an ETA would be nice to have
- [ ] give students a "help me I'm stuck" button (both at exercise and submission level; the proverbial "ask the duck" button); some students already seem to freeze when comfronted with an empty edit box on how to ask a proper question; this might bypass this freeze-moment and make it easier to ask for help (anonymously from other students)
- [ ] support [text shortcuts to include emoji](https://emojipedia.org/emoji/%F0%9F%A6%86/) as in MS Teams (e.g. `:duck:`) (#2311)
- [ ] immediately inform course admin when student has marked questions as "resolved"; if a course admin is busy answering a question, there's currently no way to get signaled
- [ ] start video chat immediately from student question (moonshot)
- [ ] activate "ask questions" for a selection of exercises (e.g. series where deadline is not expired, selected series (e.g. only exam series); suggested by Dries Benoit
- [ ] allow sending emails to course admins when a new question was asked; maybe we should bundle multiple questions in a single digest; we should allow course admins to switch on/of the option to receive emails upon questions (suggested by Dominiek Vandewalle; more info: #1788)

### question dashboard

- [x] replace "Er zijn geen vragen beschikbaar" by "Er zijn op dit moment geen onbeantwoorde vragen."
- [x] show name of course admin answering question
- [ ] combine actions of claiming a question and navigation to the submission page as a single step
- [x] add visual clue to browser tab if there are unanswered questions (c.f. new notifications on twitter) (#2275)
- [x] option to navigate through all student questions, to get a feel what has been asked/answered
- [x] provide question dashboard across all courses (only for staff or for all users that are admin for at least one course?)
- [x] provide question dashboard to students so that can trace back answers on their previous questions
- [ ] allow course admins to publish an anonymized version of question+answer as a tip & trick for an exercise, so that all students can see it (avoids duplicate questions); some tips & tricks might also be attached to the series or course level

### statistics (see also #2453)

- [ ] course level statistics about number of questions asked
- [ ] series level statistics about number of questions asked (with time period, e.g. to see how many questions for each exercise in series during last hands-on session)
- [ ] exercise level statistics about number of questions asked (number of questions per exercise could be another indicator of the difficulty of the exercise)

**Comment by bmesuere** [comment]
Comments from @charvp 
* Een last edited by bijhouden en tonen zou echt wel nuttig zijn, soms weet je niet als je naar in behandeling verplaatst of het echt jouw actie was die dat gedaan heeft of het gewoon nog niet gerefreshed was (dat impliceert dan ook dat als er eig niets veranderd is dat dat veld ook niet geüpdatet mag worden).
* Een vraag zou (voor mij iig) standaard in een nieuwe tab geopend mogen worden.
