### ISSUE TITLE
Tracking: export feature update

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#3457]
```[tasklist]
### To triage
- [x] https://github.com/dodona-edu/dodona/issues/2919
- [ ] https://github.com/dodona-edu/dodona/issues/2503
- [x] https://github.com/dodona-edu/dodona/issues/4334
- [ ] https://github.com/dodona-edu/dodona/issues/4304
- [ ] https://github.com/dodona-edu/dodona/issues/4244
- [ ] https://github.com/dodona-edu/dodona/issues/2561
- [ ] https://github.com/dodona-edu/dodona/issues/3617
- [ ] https://github.com/dodona-edu/dodona/issues/5338
- [x] auto start download when ready
```

**Comment by jorg-vr** [comment]
@bmesuere this has medium priority, but all medium priority subtasks are done.
Should I lower the priority of this issue?

**Comment by jorg-vr** [comment]
finished in https://github.com/dodona-edu/dodona/pull/5534
