### ISSUE TITLE
Tracking: JS modernization

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#3590]
The goal of this issue is to track the "older" parts of our JavaScript code. There are 3 separate parts:
- Getting rid of jQuery: this is a big library and not really needed on the modern web
- Getting rid of the old application.js file: this will unify our build setup to only use the application pack
- Migrate to typescript: better type checking

## jQuery

- [x] The bootstrap token-field and typeahead still depend on jQuery. This is only used in the course label edit. #4083 
- [x] Almost all views contain code to initialize something that is wrapped in `$(function() {})`. This can probably be replaced by a jQuery-less equivalent  #3692
- [x] jQuery in the rails views
- [x] A lot of old JS code still uses jQuery. I think there a limited number of uses:
  - Selecting elements: can easily be replaced by native JS
  - Fetching: can also be replaced by a fetch
  - Events: should also be possible to refactor without too many issues
  - Adding HTML to pages, mostly by converting strings to html elements. There is no easy replacement for this, but the template system from lit could be reused here.

## application.js

- [x] i18n: is only there because this is loaded first. Can probably move to the pack without any problems once the rest is gone https://github.com/dodona-edu/dodona/pull/3841
- [ ] ~ace: not really straightforward on how to move this. We now use a ruby gem for this that hooks into sprockets. The library has a lot of individual files for programming languages that are loaded on demand so not sure how bundling would work.~
- [x] tokenfield/typeahead: Already removed everywhere #4189
- [x] first-input-delay: No longer used to my knowledge. Can probably be removed here (and from the package file) #3591 
- [x] #4360

```[tasklist]
### TypeScript
- [x] translations.js
- [x] https://github.com/dodona-edu/dodona/pull/3921
- [x] https://github.com/dodona-edu/dodona/pull/4083
- [x] https://github.com/dodona-edu/dodona/pull/4209
- [x] https://github.com/dodona-edu/dodona/pull/3930
- [x] https://github.com/dodona-edu/dodona/pull/4267
- [x] https://github.com/dodona-edu/dodona/pull/3963
- [x]  https://github.com/dodona-edu/dodona/pull/4618 
- [x] https://github.com/dodona-edu/dodona/pull/3593
- [x] https://github.com/dodona-edu/dodona/pull/4080
- [x] https://github.com/dodona-edu/dodona/pull/4463
- [x] https://github.com/dodona-edu/dodona/pull/4298
- [x] https://github.com/dodona-edu/dodona/pull/4465
- [x] https://github.com/dodona-edu/dodona/pull/4266
- [x] https://github.com/dodona-edu/dodona/pull/4023
- [x] https://github.com/dodona-edu/dodona/pull/4127
- [ ] #4849 
```

**Comment by bmesuere** [comment]
If #4189 gets merged, the ace editor is the only remaining asset in application.old.js. We use an (outdated) rails gem to add support using the sprockets pipeline. The problem with this library is that it contains A LOT of plugins to support all languages. These are loaded on demand (by file name) to keep the default package size small-ish.

There are a number of alternatives to remove this last remaining entry
- use a hosted CDN version of the editor: we try to avoid this, should be the last resort
- find an alternative rails integration: I haven't found one
- bundle everything into a single file with our webpack pipeline: the file size will be huge
- vendor it: manually in the public folder or by adding it to our package file and copy the files to the public folder in a build step (also see https://github.com/ajaxorg/ace-builds/)
- use a different editor. For papyros we use codemirror, for dolos we use monaco.

If this is done, the old application.js file can be removed but this also means that the sprockets gem and its config and deployment stuff can probably be removed.

**Comment by bmesuere** [comment]
As an update to my previous comment: Sprockets is still used for the newer JS as well, so it can't be removed. What we can do is leave ace as is, but rename the file from application_old to ace editor and only include it where needed.
