### ISSUE TITLE
Tracking server maintenance

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#3712]
## After exams
- [x] Rails/passenger config update
- [x] Dodona release
- [x] Announce UGent DRP test of 11/07
- [x] Use Calliope as memcached server (first check installation and firewall) #3761

## Scheduled maintenance
- [x] Check if/when we can upgrade to Ubuntu 22.04 LTS (do we need the .1 release which is only planned for 04/08?)
- [x] Coordinate VM upgrades with DICT
  - [x] Elysium 2 cores (can be done after calliope migration)
  - [x] Pandora 2 cores (can be done after exams)
  - [x] Phocus 2 cores (can be done when we want)
  - [x] Increase Phocus disk to 100GB (can be done when we want)
  - [x] Increase Naos disk to 100GB (can be done when we want)
  - [x] Increase worker disk to 75GB
  - [x] Increase Dodona disk to 100GB
- [x] Announce downtime
- [x] Test upgrade one of the workers
- [x] Upgrade non-critical servers
  - [x] Workers one by one
  - [x] Phocus
  - [x] Pandora 
  - [x] Elysium
  - [x] Naos
  - [x] Mestra
  - [x] Dolos
  - [x] Hermione
- [x] Upgrade servers with downtime
  - [x] Dodona
  - [x] Lethe
  - [x] Calliope

**Comment by bmesuere** [comment]
> Upgrades from one LTS to the next LTS release are only available after the first point release. For example, Ubuntu 18.04 LTS will only upgrade to Ubuntu 20.04 LTS after the 20.04.1 point release. If users wish to update before the point release (e.g. on a subset of machines to evaluate the LTS upgrade) **users can force the upgrade via the -d flag**.

So `sudo do-release-upgrade -d` should work.

**Comment by chvp** [comment]
`memcached` being unavailable does not induce downtime. Only the few graphs that are only served from cache will be unavailable for a bit.

**Comment by rien** [comment]
I resized phocus with the following steps:

- backup `/var/lib/graphite`
- `sudo swapoff /dev/sda5` turn off swap
 - edit partitions using `parted`:
    -  `rm 2` and `rm 5` to remove swap and unused partition
    -  `resizepart 1` resize main partition (size was prompted)
    -  `mkpart` create new swap parition
 - `resize2fs /dev/sda1` grow filesystem to the available size
 -  `mkswap /dev/sda2` create swap filesystem
 - edit fstab with the new swap fs uuid, the main fs uuid was not changed
 - reboot

**Comment by bmesuere** [comment]
Phocus dist upgrade log
- `sudo apt update && sudo apt upgrade`
- reboot to check if everything still works
- `sudo do-release-upgrade -d` (took about 15 minutes)
- reboot

-> graphite seems to be broken, all requests to the graphite endpoint return an error 500 but none of the logs I checked contains a trace. @beardhatcode any idea?

**Comment by bmesuere** [comment]
Workers needed a `rvm reinstall 3.2.1` and `bundle pristine` to fix ssl lib errors.

**Comment by bmesuere** [comment]
All workers now use a swap file using these commands:
```
sudo fallocate -l 2G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
sudo pico /etc/fstab
```
And replace the swapfile line by
```
/swapfile swap swap defaults 0 0
```
