### ISSUE TITLE
Tracking issue: notifications

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#4065]
With the start of the academic year, we're seeing a barrage of notifications. This significantly reduces the usefulness of them which causes us to overlook actual issues.

- [x] The images are missing from the grafana slack notifications: https://github.com/grafana/grafana/discussions/38030#discussioncomment-2816887
- [ ] There are too many "long request" notifications: check if we should increase the threshold (e.g., 10s instead of 5) or ask DICT if something is wrong with the storage
- [x] DB swap notifications: restart the database server? 
- [x] Web server load notification: alerts if the load is over 0.8 or so but this is not a problem on a 6-core machine
- [x] See if we can point the slack notifications to dash.dodona.be instead of phocus 
- [ ] Remove grafana from phocus logcheck (@rien)
- [x] Introduce a priority system of some kind (or a separate channel?) to discern between info (slow page load, internal error for submission) and actual alerts.

**Comment by jorg-vr** [comment]
I have installed https://grafana.com/grafana/plugins/grafana-image-renderer/#installation on phocus.ugent.be
And set the config settings specified [here](https://grafana.com/docs/grafana/latest/alerting/images-in-notifications/) in `/etc/grafana/grafana.ini`

i did not setup an external image drive.

Hopefully this is enough to get images in our notifications again

**Comment by chvp** [comment]
Did we not already have grafana-image-renderer installed? It definitely user to work in the past.

**Comment by bmesuere** [comment]
@chvp yes, but things broke due to grafana changes.

Alerts used to be coupled with panels which could then be rendered and added to notifications.

In more recent versions of grafana, alerts were refactored to be stand alone things which means there is no longer a graph associated with them.

After complaints, they added the functionality back, but it isn't straightforward to get is working. In any case, it still isn't working: https://dodona-edu.slack.com/archives/CNM1KVA56/p1665230614653479
