### ISSUE TITLE
Tracking: Revisit the questions feature

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#4361]
```[tasklist]
### Triaged
- [ ] https://github.com/dodona-edu/dodona/issues/2826
- [ ] https://github.com/dodona-edu/dodona/issues/2827
- [ ] https://github.com/dodona-edu/dodona/issues/3151
- [ ] https://github.com/dodona-edu/dodona/issues/4525
- [ ] https://github.com/dodona-edu/dodona/issues/4641
```

```[tasklist]
### To be decided 
- [ ] #2329
- [ ] https://github.com/dodona-edu/dodona/issues/2355
```

**Comment by jorg-vr** [comment]
Do I close this or lower priority as all decided features are done?

**Comment by bmesuere** [comment]
I think this is done for now. Nice improvements 👍
