### ISSUE TITLE
Tracking: Repository fixes

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#4362]
```[tasklist]
- [ ] #4380 
- [ ] #4381 
- [ ] #4382
- [ ] #3430 
- [x] The placeholder for the clone url on the repositories/new page mentions github.ugent.be. While correct, github.com would be more logical. From #4240
- [x] When adding a repo, add a better error message when permissions are missing. From #4240
- [x] The learning activities table (at least the one on the repo page) has no empty state. From #4240
- [x] When adding a repository, the existing exercises were not added automatically. (needs to be double checked) From #4240
- [ ] https://github.com/dodona-edu/dodona/issues/4402
- [ ] https://github.com/dodona-edu/dodona-edu.github.io/pull/231
- [x] add link of judge overview to repo page
```

**Comment by bmesuere** [comment]
About the judge selection: I don't think we can really solve this right now. Instead, I suggest we add a page to the documentation website containing an overview of all judges with a 1 paragraph description (and a link to more in depth docs, example exercises,...)

We can link to that page from the form on Dodona.

**Comment by chvp** [comment]
Can't we solve this by introducing an n*n relationship between programming languages and judges, with an optional comment that can be shown? (Relying on manual data entry.)

**Comment by bmesuere** [comment]
Once we have tested up and running for single programming languages such as c# and Python, I would indeed add them as a separate "fake" option to the selection.
