### ISSUE TITLE
Tracking: Evaluations

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#4364]
```[tasklist]
### Related
- [ ] #2443
- [ ] https://github.com/dodona-edu/dodona/issues/2817
- [ ] https://github.com/dodona-edu/dodona/issues/2823
- [ ] https://github.com/dodona-edu/dodona/issues/2861
- [ ] https://github.com/dodona-edu/dodona/issues/4073
- [ ] https://github.com/dodona-edu/dodona/issues/4171
- [ ] https://github.com/dodona-edu/dodona/issues/4174
- [ ] #4173 
```

**Comment by jorg-vr** [comment]
Two more evaluation related feature requests by teachers:
1. Make it possible to disable access to other courses/previous exercises during a test (IE support for closed book testing)
2. Make it possible to export grades to smartschool
