### ISSUE TITLE
Tracking: saved annotation feedback

### ISSUE THREAD

**Issue by jorg-vr** [dodona-edu/dodona#4564]
### Feature requests
- [ ]  Broader annotation scope
  Some comments can be relevent for every exercise in a course
  Or for the same exercise in different courses
  Or for multiple admins of the same course
  - https://github.com/orgs/dodona-edu/discussions/4064#discussion-4446267
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4123290
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4128124
  
conclusions after discussion:
- dont share annotations between users
- determine scope when saving
- possible scopes: exercise, course, global
Timing:  version 2

- [x] **Don't require anticipations of reuse**
  Make it posible to search for annotations that have not been 'marked' for reuse
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-3801922
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4134181

Conclusions after discussion:
- create annotations index page with search
- can expand saved annotations index page
Timing: version 1/2?
  
  
### Enhancements
- [x] **Use arrow keys to select saved annotaion**
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4119363
 Timing version 1
  
- [ ] **order saved annotation by most recently used/added**
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4117857
Timing: depends on research CHVP
  
- [x] **allow editing saved annotation by clicking 'linked' icon**
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4118022 But I would not display the title inline
COD:
- Rethink link icon (Could create wrong expectations) => comment bank
- Open separate page for saved_annotation
> from https://github.com/dodona-edu/dodona/pull/4701#pullrequestreview-1562299868: when picking a suggestion, the "save annotation" checkbox is disabled, but it is also shown as checked which might be confusion. Maybe replace it with a link to the page where you can edit that annotation?

Timing: version 1
  
<del>

- [ ] **allow updating all usages of a saved annotation**
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-5228124
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4118151
 Timing: never
  
- [ ] **Allow multiple language versions of saved annotations**
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4118189
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4128124
Timing: never
  
- [ ] **Suport markdown in saved annotation titles**
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4118310
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4123447
 Timing: never

</del>
  
- [x] **Make saved annotations table sortable and filtarable**
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4123312
 COD:
 - see index page issue above
  
- [x] **Link to usages from a saved annotation**
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4127861
COD:
- could be shown on annotation show page
Timing: version 1
  
- [x] **allow saved annotations with the same name**
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4123485
COD:
- warning instead of error on non unique name
Timing: version 1
  
- [x] **Put reuse annotation field below input field and reuse it as title:**
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4882739
 COD:
- Try out a side by side approach
Timing: version1

- [x] **Disable saving already saved annotation**
- show checked when disabled with saved annotation title
Timing: version 1

- [x] **Inline save annotation title field**
- save horizontal space
Timing: version 1

- [x] **Remove right sidebar**
Timing: version 1
  
### Bugs
  
- [x] **Pressing tab in an empty searchfield selects an unshown option**
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4123096
  
- [x] **First field of form should be focussed**
  Either swap form order or focus first field
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4123096
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4882739
  
<del>
- [ ] **When the cursor is halfway inside a comment, page-up scrolls the page down.**
  - https://github.com/orgs/dodona-edu/discussions/4064#discussioncomment-4137337
</del>
Cannot reproduce

**Comment by jorg-vr** [comment]
- [ ] Should also be able to save an annotation when updating it
