### ISSUE TITLE
2024 server update

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#5370]
During early summer, we'll once again update our servers. This issue aims to gather tasks we come up with during the next few months.

- [x] Upgrade all servers to ubuntu 24.04
- [x] #5092 
- [x] Turn off Pandora and remove it from ansible
- [x] Upgrade ruby to 3.3 (might need some code changes and additional checks and tests first)
- [x] Switch to Trilogy if https://github.com/trilogy-libraries/trilogy/issues/26 gets implemented by then
