### ISSUE TITLE
explore Jupyter Notebooks as execution environment for contexts

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#98]
Explore the use of [Jupyter Notebooks](http://jupyter.readthedocs.org/en/latest/install.html) as an environment for executing and partially evaluating all testcases in a context. 

The Jupyter Notebooks has a good model for **kernels** (interactive execution environments) and [list of kernels for different programming languages](https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages) (including Python, JavaScript, Bash, Java, Haskell, ...) has already been implemented.

### TODO
- [x] run sequence of statements in IPython Notebook kernel
- [x] timeout statement execution
- [x] provide information on stdin for statement execution
- [x] handle case where an attempt is made to read from stdin, with no more information available (EOF)
- [x] put size limit on buffers for `stdout` and `stderr` (see [here](https://github.com/jupyter/notebook/pull/506) and [here](https://github.com/ipython/ipython/issues/6516))
- [x] merge content coming from the same stream (stdout, stderr) because it can be sent in chunks
- [x] test with kernels supporting languages other than Python 
  - [x] IRkernel: stdout and stderr are not properly captured by the kernel
  - [x] IJulia: OK, but slow startup
- [x] restart kernel after client reports an error (time limit exceeded, request for stdin that is exhausted, output buffer overrun, ...); otherwise kernel has to be shutdown and restarted if it needs to be reused after client-side error
- [ ] launch IPython Notebook kernel in Docker image (see [tmpnb](https://github.com/jupyter/tmpnb) or [docker-stacks](https://github.com/jupyter/docker-stacks))
- [ ] run output processor in IPython Notebook kernel (same or different namespace as submission statements; implement using [notebook extensions](http://mindtrove.info/4-ways-to-extend-jupyter-notebook/) ??)
- [ ] evaluate runtime overhead of launching IPython Notebook kernel and executing statements remotely using [IPython Wire Protocol](http://ipython.readthedocs.io/en/stable/)
- [ ] include runtime metrics in kernel messages (see [notebook extensions](http://mindtrove.info/4-ways-to-extend-jupyter-notebook/) and [ipython-autotime extension](https://github.com/cpcloud/ipython-autotime))
- [ ] see if there is a way to provide stdin in one big chunk instead of line-per-line, which could be much more efficient for large volumes of data on stdin; this, however, would not allow to stop early if server requests for input that no longer exists, if this case is not handled server-side

_[Original issue](https://github.ugent.be/dodona/dodona/issues/98) by @pdawyndt on Mon Aug 01 2016 at 12:12._
